version: "3"

services:
  vscsrv:
    build: ./docker/vscode-server/arm64
    volumes:
      - "/home/ubuntu/.vscode-cli/token.json:/root/.vscode-cli/token.json"
      - "/home/ubuntu/.vscode-cli/code_tunnel.json:/root/.vscode-cli/code_tunnel.json"
      - "/home/ubuntu/.vscode-cli/license_consent.json:/root/.vscode-cli/license_consent.json"
      - "/home/ubuntu/.vscode-cli/server-insiders:/root/.vscode-cli/server-insiders"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "REPO_URL=https://github.com/aaaa777/vfy-testing-cicd.git"
